### ISSUE TITLE
Add custom version of Peter Han's PLib libraries to source control

### ISSUE THREAD

**Issue by cameron-sjo** [Truinto/ONI-Modloader-SimpleMods#23]
Hey there, 

I was hoping to try and fix my other issue that I created, #21. 

I pulled down the code, and I've been working through trying to get it to build. Based on what I've found, I think you're using a modified version of the PLib libraries. I couldn't find the modifications in your fork. Is it possible for you to add that assembly?

Looks like it's referenced by your Directory.Build.props, in the `./packages` directory.

**Comment by Truinto** [comment]
Oh no. I did not check this page for ages. Sorry for the late answer. Usually I get a notification when someone posts here.

The fork you look for is this: 
https://github.com/Truinto/ONIMods-PeterHan

I honestly did not think anyone would try to build this. So I was a bit careless about it. Since PeterHan has his code under MIT, I will push the libs into a public folder.

**Comment by Truinto** [comment]
One more thing. I have an empty file "_IsDLC1" in my ONI game path. It's required for some build flags. This was at a time, when I had to swap the installations for the vanilla/DLC builds. Klei merged these, so thankfully DLC builds work in vanilla again and this swapping isn't necessary anymore.
