### ISSUE TITLE
Liquid reservoir ignoring max Limit

### ISSUE THREAD

**Issue by XXilay** [Truinto/ONI-Modloader-SimpleMods#37]
Basically just limiting the liquid reservoir to less than 99T will still make it fill up past that limit till 99t

Make a liquid reservoir , connect a pipe to both input and output sides and then limit it.

There are no Debug Logs in the Steam ONI folders from what I found

Heres the screenshot using 10T of liquid limit: https://imgur.com/a/HJy0Ykl

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version U43-526946-5

[Player.log](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/9842820/Player.log)

**Comment by Truinto** [comment]
That works as intended. The slider sets the logic output and instructs dupes on how much they can store there. Pipes ignore those limitations. If this behavior has been changed since I played the game, then I am not aware of it.

Tho if you want to limit the input, you can just install a shut off valve and connect it to the logic output. Or you disable the feature that allows dupes to store bottles directly in reservoirs.
