### ISSUE TITLE
Customize Buildings: Crash caused by recent fix to farm tiles; possible mod conflict

### ISSUE THREAD

**Issue by TroublesomeCorvid** [Truinto/ONI-Modloader-SimpleMods#43]
I'm not certain as to exactly *how* to reproduce this crash, but hopefully these log files will help.

If you need the output_log file as well, please let me know - it's over GitHub's 25 MB file size limit, so I'll need to use something like Pastebin.com to get it to you.
[oopsa-daisey.txt](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/12552940/oopsa-daisey.txt)
[Player.log](https://github.com/Truinto/ONI-Modloader-SimpleMods/files/12552941/Player.log)

**Comment by Truinto** [comment]
UnityEngine.GameObject.GetComponentFastPath somehow makes a NullReferenceException. What OS do you work on?

**Comment by TroublesomeCorvid** [comment]
Full details, just on the off-hand chance it matters...

Edition:	Windows 10 Home
Version:	22H2
Installed on:	‎2020-‎10-‎02
OS build:	19045.3324
Experience:	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by Truinto** [comment]
I thought it might be a compatibilty issue. But the log proofs otherwise. I thought it might be an implimitation problem, but you run on the same OS. No idea why my machine would work and yours not.
In any case, I added a try-catch block which will prevent this crash. Worst case, your auto arm works normally (with no extra features).

**Comment by TroublesomeCorvid** [comment]
Well, it seems to be working just fine now - hours of gameplay and no crashes caused by sweepers.  Only crashes caused by Advanced Flow Management, but I'm sure that Glampi is working on it.  :)

Thanks much!
