### ISSUE TITLE
Better explanation for Air Conditioner Absolute Power Factor, please?

### ISSUE THREAD

**Issue by TroublesomeCorvid** [Truinto/ONI-Modloader-SimpleMods#48]
![Capture](https://github.com/Truinto/ONI-Modloader-SimpleMods/assets/54051273/53687556-48b7-43a6-8722-e31d5a19ad46)
The tool tip for this feature is a bit difficult to understand, and there's nothing about it in the README text here on GitHub.  Can we get a better explanation on how this works?

I mean, I think I get it?  That it's a multiplier for how many watts it uses per kDPU of heat moved?  But I can't figure out the math behind it.  Probably because of the 1.2kW hard limit on the aquatuner?

**Comment by Truinto** [comment]
`Math.Min(energyConsumer.WattsNeededWhenActive, 100f + (Math.Abs(CurrentDPU) * energyConsumer.WattsNeededWhenActive / (MaxDPU * CustomizeBuildingsState.StateManager.State.AirConditionerAbsolutePowerFactor)))`

In text: Power consumption is 100W plus [heat transfered] * 1200kW / (10000 * factor); but at most 1200kW

Or simply: power from 0 to 100% of the base power consumption relative to the heat transfer up to 10kDPU. Plus 100 Watts base cost.

I did this because the factor felt always bad. An extra flat 100 Watt cost feels more natural, imo.

**Comment by Truinto** [comment]
Btw, if you set this to a large enough number, it will just work vanilla at 12kW.
